vnoremap <C-c> "+y
set nu
set ignorecase
set smartcase
set incsearch
set hlsearch
set title
set mouse=a
set wildmode=longest,list,full
nnoremap C :%!
nnoremap D :%d<cr>
nnoremap S :%s//gI<Left><Left><Left>
nnoremap s :update<cr>
nnoremap z :update \| q<cr>
"""""""""""" POWERLINE """"""""""""""""""""""""""
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

set laststatus=2
""""""""""" END """""""""""""""""""""""""""
